adminStoreFile=../keystores/locosporti-admin.jks
adminStorePassword=locosporti-admin
adminKeyAlias=locosporti-admin
adminKeyPassword=locosporti-admin

clienteStoreFile=../keystores/locosporti-cliente.jks
clienteStorePassword=locosporti-cliente
clienteKeyAlias=locosporti-cliente
clienteKeyPassword=locosporti-cliente